[toolchain]
anchor_version = "0.30.1"

[features]
resolution = true
skip-lint = false

[programs.devnet]
sooth_core = "55kGEMHJyNbD3qcdonCD8UPTqzM85yg2kr6M5UF5P353"

[programs.localnet]
sooth_core = "55kGEMHJyNbD3qcdonCD8UPTqzM85yg2kr6M5UF5P353"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[workspace]
members = [
    "packages/programs-core/programs/sooth-core",
]

[scripts]
test = "pnpm -r test"
