[toolchain]
anchor_version = "0.30.1"

[features]
resolution = true
skip-lint = false

[programs.devnet]
sooth_core = "EwiENXxrU3PEdmzCttJp9viCR6JZaFnFs3aW9n9a3EWw"

[programs.localnet]
sooth_core = "EwiENXxrU3PEdmzCttJp9viCR6JZaFnFs3aW9n9a3EWw"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[workspace]
members = [
    "packages/programs-core/programs/sooth-core",
]

[scripts]
test = "pnpm -r test"
