// Single-program re-export of the Anchor IDL JSON for `sooth_core`.
// The JSON file is generated by `anchor idl build` against the on-chain
// program (see `packages/programs-core`); IDL spec: 0.1.0 (Anchor 0.30+
// format). Compatible with `@coral-xyz/anchor` 0.30.x at runtime.

import soothCoreIdl from "./sooth_core.json" with { type: "json" };
export { soothCoreIdl };
export type SoothCoreIdl = typeof soothCoreIdl;
