// The redesigned book's event decoder.
//
// This is a SECOND implementation of a decoder that also lives in
// `@sooth/sdk-solana`, because this service deliberately has no SDK
// dependency — the indexer stays deployable without the client toolchain.
//
// The risk that creates is drift: two decoders of one wire format, either of
// which can be wrong on its own. So the fixture here is bytes captured from a
// real on-chain transaction (see `fixtures/bookfilled.bin`, generated by the
// SDK's LiteSVM suite), and both decoders are pinned against it rather than
// against each other.

import { readFile } from "node:fs/promises";
import { join } from "node:path";

import { describe, expect, it } from "vitest";

import {
  BOOK_EVENT_VERSION,
  BOOK_FILLED_DISCRIMINATOR,
  CPI_EVENT_TAG,
  decodeBookEventInstructionData,
  decodeBookEventsFromTransaction,
  type BookFilledEvent,
} from "../src/decode-book-events.js";
import { PROGRAM_IDS } from "../src/config.js";
import { encodeBase58 } from "./helpers/base58.js";

const fixturePath = join(import.meta.dirname, "fixtures", "bookfilled.bin");

async function fixture(): Promise<Uint8Array> {
  return new Uint8Array(await readFile(fixturePath));
}

describe("book event decoder", () => {
  it("decodes a captured BookFilled inner instruction", async () => {
    const data = await fixture();
    expect(Buffer.from(data.slice(0, 8))).toEqual(Buffer.from(CPI_EVENT_TAG));
    expect(Buffer.from(data.slice(8, 16))).toEqual(
      Buffer.from(BOOK_FILLED_DISCRIMINATOR),
    );

    const ev = decodeBookEventInstructionData(data) as BookFilledEvent;
    expect(ev).not.toBeNull();
    expect(ev.kind).toBe("book_filled");
    expect(ev.version).toBe(BOOK_EVENT_VERSION);
    expect(ev.fills.length).toBeGreaterThan(0);
    for (const f of ev.fills) {
      // The unified axis quotes everything as the YES price, so a tick is
      // directly usable — no complement flip, which is the exact mistake that
      // made the legacy book emit its two ticks swapped (bug B2).
      expect(f.price_tick).toBeGreaterThanOrEqual(1);
      expect(f.price_tick).toBeLessThanOrEqual(999);
      expect(f.amount).toBeGreaterThan(0n);
    }
    expect(ev.ts).toBeGreaterThan(0n);
  });

  it("returns null for anything that is not a book event", () => {
    // Quiet skip, so an unrelated inner instruction cannot break a scan.
    expect(decodeBookEventInstructionData(new Uint8Array(4))).toBeNull();
    expect(decodeBookEventInstructionData(new Uint8Array(64))).toBeNull();
    const wrongDisc = new Uint8Array([...CPI_EVENT_TAG, ...new Uint8Array(64)]);
    expect(decodeBookEventInstructionData(wrongDisc)).toBeNull();
  });

  it("rejects an unknown version instead of mis-parsing it", async () => {
    const data = await fixture();
    expect(decodeBookEventInstructionData(data)).not.toBeNull();

    const bumped = Uint8Array.from(data);
    bumped[16] = 2; // version byte — first field of the body
    expect(() => decodeBookEventInstructionData(bumped)).toThrow(
      /unsupported book event version 2/,
    );
  });

  it("rejects trailing bytes rather than silently truncating", async () => {
    const data = await fixture();
    const extended = new Uint8Array([...data, 0, 0, 0]);
    expect(() => decodeBookEventInstructionData(extended)).toThrow(
      /trailing bytes/,
    );
  });

  it("rejects a truncated payload rather than reading past the end", async () => {
    const data = await fixture();
    const short = data.slice(0, data.length - 4);
    expect(() => decodeBookEventInstructionData(short)).toThrow(/truncated/);
  });

  it("finds the event inside a transaction and ignores other programs", async () => {
    const data = await fixture();
    const OTHER = "11111111111111111111111111111111";
    const tx = {
      transaction: {
        message: { accountKeys: [OTHER, PROGRAM_IDS.SOOTH_CORE] },
      },
      meta: {
        err: null,
        innerInstructions: [
          {
            index: 0,
            instructions: [
              // Not ours — must be skipped, not throw.
              { programIdIndex: 0, data: encodeBase58(new Uint8Array([1, 2, 3])) },
              { programIdIndex: 1, data: encodeBase58(data) },
            ],
          },
        ],
      },
    };
    const events = decodeBookEventsFromTransaction(tx);
    expect(events).toHaveLength(1);
    expect(events[0]!.kind).toBe("book_filled");
  });

  it("ignores an event emitted by a different program id", async () => {
    // A self-CPI event is authentic because the program emits it under its own
    // id, so the program filter IS the authenticity check.
    const data = await fixture();
    const IMPOSTOR = "11111111111111111111111111111111";
    const tx = {
      transaction: { message: { accountKeys: [IMPOSTOR] } },
      meta: {
        err: null,
        innerInstructions: [
          { index: 0, instructions: [{ programIdIndex: 0, data: encodeBase58(data) }] },
        ],
      },
    };
    expect(decodeBookEventsFromTransaction(tx)).toEqual([]);
  });
});
